-- 001
CREATE TABLE customer (
  id INT PRIMARY KEY,
  name VARCHAR(50)
);

-- 002
ALTER TABLE Customer
ALTER COLUMN name SET DATA TYPE varchar(60);

-- 003
ALTER TABLE Customer
ADD COLUMN phone VARCHAR(10);